// Samples the puzzle's secret target points from a configured region of the
// photo and pre-renders the matching "shard" crops. The browser only ever
// receives these opaque crops (by index) — never the coordinates — so the answer
// mapping stays server-side.
//
// Edit worker/src/puzzle.config.json (region / count / spacing), then run:
//
//   node scripts/generate-pieces.mjs
//
// It writes worker/src/targets.json (consumed by the Worker) and public/pieces.
//
import sharp from 'sharp'
import { mkdir, readFile, rm, writeFile } from 'fs/promises'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(root, 'public', 'nuke-cloud.png')
const OUT_DIR = join(root, 'public', 'pieces')
const CONFIG = join(root, 'worker', 'src', 'puzzle.config.json')
const TARGETS = join(root, 'worker', 'src', 'targets.json')

const cfg = JSON.parse(await readFile(CONFIG, 'utf8'))
const { radius, tolerance, count, region } = cfg
const minSpacing = cfg.minSpacing ?? 0.06

const rnd = (a, b) => a + Math.random() * (b - a)
const round = n => Math.round(n * 1000) / 1000

// Rejection-sample `count` points inside the region, keeping them spaced out.
// Relax the spacing if the region is too tight to fit them all.
const sample = () => {
  for (let spacing = minSpacing; spacing >= 0.01; spacing -= 0.01) {
    const pts = []
    for (let attempt = 0; attempt < count * 400 && pts.length < count; attempt++) {
      const x = rnd(region.x[0], region.x[1])
      const y = rnd(region.y[0], region.y[1])
      if (pts.every(p => Math.hypot(p.x - x, p.y - y) >= spacing)) {
        pts.push({ x, y })
      }
    }
    if (pts.length === count) return pts
  }
  throw new Error(`could not place ${count} points in region with any spacing`)
}

const targets = sample().map(p => ({ x: round(p.x), y: round(p.y) }))

const meta = await sharp(SRC).metadata()
const W = meta.width
const H = meta.height
const side = Math.round(2 * radius * W)
const clamp = (v, min, max) => Math.min(max, Math.max(min, v))

await rm(OUT_DIR, { recursive: true, force: true })
await mkdir(OUT_DIR, { recursive: true })

for (let i = 0; i < targets.length; i++) {
  const t = targets[i]
  const left = clamp(Math.round(t.x * W - side / 2), 0, W - side)
  const top = clamp(Math.round(t.y * H - side / 2), 0, H - side)
  await sharp(SRC)
    .extract({ left, top, width: side, height: side })
    .resize(240, 240)
    .webp({ quality: 82 })
    .toFile(join(OUT_DIR, `piece-${i}.webp`))
  console.log(`piece-${i}.webp  <-  (${t.x}, ${t.y})  [${left},${top} ${side}x${side}]`)
}

await writeFile(
  TARGETS,
  JSON.stringify(
    {
      note: 'GENERATED by scripts/generate-pieces.mjs from worker/src/puzzle.config.json — do not edit by hand.',
      radius,
      tolerance,
      targets,
    },
    null,
    2,
  ) + '\n',
)

console.log(
  `\n${targets.length} pieces written to public/pieces; targets.json updated ` +
    `(region x[${region.x}] y[${region.y}], source ${W}x${H}, crop ${side}px)`,
)
